import { LayoutSchema, TamboComponent } from '@/types';

export class CodeExporter {
    // React/TypeScript Export
    exportReact(schema: LayoutSchema): string {
        return `// Generated by PromptCraft AI
// ${schema.name}
// ${schema.description}

import React from 'react';
import { TamboRenderer } from './tamboRenderer';

const schema = ${JSON.stringify(schema, null, 2)};

export const ${this.toPascalCase(schema.name)} = () => {
  return (
    <div className="min-h-screen bg-slate-950">
      <TamboRenderer components={schema.components} />
    </div>
  );
};

export default ${this.toPascalCase(schema.name)};
`;
    }

    // HTML/CSS Export
    exportHTML(schema: LayoutSchema): string {
        const componentsHTML = schema.components
            .map(c => this.componentToHTML(c))
            .join('\n');

        return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${schema.name}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: #020617;
            color: #f1f5f9;
            padding: 2rem;
        }
        
        .container {
            max-width: 1400px;
            margin: 0 auto;
            display: grid;
            grid-template-columns: repeat(12, 1fr);
            gap: 1.5rem;
        }
        
        .component {
            background: rgba(30, 41, 59, 0.5);
            border: 1px solid rgba(71, 85, 105, 0.3);
            border-radius: 1rem;
            padding: 1.5rem;
            backdrop-filter: blur(10px);
        }
        
        .component h2 {
            font-size: 1.5rem;
            margin-bottom: 0.5rem;
            color: #e0e7ff;
        }
        
        .component h3 {
            font-size: 1.25rem;
            margin-bottom: 1rem;
            color: #c7d2fe;
        }
        
        .component p {
            color: #94a3b8;
            line-height: 1.6;
        }
        
        .stat-card {
            text-align: center;
        }
        
        .stat-value {
            font-size: 2.5rem;
            font-weight: bold;
            color: #818cf8;
            margin: 1rem 0;
        }
        
        .stat-trend {
            color: #34d399;
            font-weight: 600;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
        }
        
        th, td {
            padding: 0.75rem;
            text-align: left;
            border-bottom: 1px solid rgba(71, 85, 105, 0.3);
        }
        
        th {
            color: #e0e7ff;
            font-weight: 600;
        }
        
        td {
            color: #cbd5e1;
        }
    </style>
</head>
<body>
    <div class="container">
${componentsHTML}
    </div>
</body>
</html>`;
    }

    // Vue.js Export
    exportVue(schema: LayoutSchema): string {
        return `<!-- Generated by PromptCraft AI -->
<!-- ${schema.name} -->
<!-- ${schema.description} -->

<template>
  <div class="min-h-screen bg-slate-950 p-8">
    <div class="max-w-7xl mx-auto grid grid-cols-12 gap-6">
      <component
        v-for="comp in components"
        :key="comp.id"
        :is="getComponentType(comp.type)"
        :style="getGridStyle(comp.layout)"
        v-bind="comp.props"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const components = ref(${JSON.stringify(schema.components, null, 2)});

const getComponentType = (type: string) => {
  // Map to your Vue components
  return type;
};

const getGridStyle = (layout: any) => {
  return {
    gridColumn: \`span \${layout.width}\`,
    gridRow: \`span \${layout.height}\`
  };
};
</script>

<style scoped>
/* Add your styles here */
</style>
`;
    }

    // JSON Schema Export
    exportJSON(schema: LayoutSchema): string {
        return JSON.stringify(schema, null, 2);
    }

    // Helper methods
    private componentToHTML(component: TamboComponent): string {
        const { layout } = component;
        const style = `grid-column: span ${layout?.width || 12}; grid-row: span ${layout?.height || 4};`;

        switch (component.type) {
            case 'Header':
                return `        <div class="component" style="${style}">
            <h2>${component.props.title || 'Header'}</h2>
            <p>${component.props.subtitle || ''}</p>
        </div>`;

            case 'Card':
                return `        <div class="component stat-card" style="${style}">
            <h3>${component.props.title || 'Card'}</h3>
            <div class="stat-value">${component.props.value || '0'}</div>
            <div class="stat-trend">${component.props.trend || ''}</div>
            <p>${component.props.description || ''}</p>
        </div>`;

            case 'Table':
                const columns = component.props.columns || [];
                const data = component.props.data || [];
                return `        <div class="component" style="${style}">
            <h3>${component.props.title || 'Table'}</h3>
            <table>
                <thead>
                    <tr>
                        ${columns.map((col: string) => `<th>${col}</th>`).join('')}
                    </tr>
                </thead>
                <tbody>
                    ${data.map((row: any) => `
                    <tr>
                        ${Object.values(row).map(val => `<td>${val}</td>`).join('')}
                    </tr>`).join('')}
                </tbody>
            </table>
        </div>`;

            default:
                return `        <div class="component" style="${style}">
            <h3>${component.type}</h3>
            <p>${JSON.stringify(component.props)}</p>
        </div>`;
        }
    }

    private toPascalCase(str: string): string {
        return str
            .replace(/[^a-zA-Z0-9]/g, ' ')
            .split(' ')
            .filter(word => word.length > 0)
            .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
            .join('');
    }
}

export const codeExporter = new CodeExporter();
